Time, LogLevel, Message
2021_10_12_20_48_58,Information,"Task: Reload task of test"
2021_10_12_20_48_58,Information,"Proxy: https://qtarchlabus04"
2021_10_12_20_48_58,Information,"Wait: 31 seconds"
2021_10_12_20_48_58,Information,"Poll: 15 seconds"
2021_10_12_20_48_58,Information,"Log: C:\Users\qmi\Source\Repos\QlikSenseTask\QlikSenseTaskSource-3.X\QlikSenseTask\bin\Release"
2021_10_12_20_48_58,Information,"Delete Log: -90 days"
2021_10_12_20_48_58,Information,"Creating connection..."
2021_10_12_20_48_58,Debug,"Creating web connection..."
2021_10_12_20_48_58,Debug,"Creating CookierAwareWebClient..."
2021_10_12_20_48_58,Debug,"calling /qrs/about"
2021_10_12_20_48_58,Debug,"setting headers"
2021_10_12_20_48_58,Debug,"constructing query string"
2021_10_12_20_48_58,Debug,"calling https://qtarchlabus04/qrs/about"
2021_10_12_20_49_00,Debug,"error: The remote name could not be resolved: 'qtarchlabus04'"
2021_10_12_20_49_01,Error,"System.Exception: Couldnt connect to the server at https://qtarchlabus04 , check that the Proxy and QRS are running.  Message: Object reference not set to an instance of an object.
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger) in C:\Users\qmi\Source\Repos\QlikSenseTask\QlikSenseTaskSource-3.X\QlikSenseTask\QRSNTLMWebClient.cs:line 44
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger) in C:\Users\qmi\Source\Repos\QlikSenseTask\QlikSenseTaskSource-3.X\QlikSenseTask\QlikSenseJSONHelper.cs:line 27
   at QlikSenseTask.Program.Main(String[] args) in C:\Users\qmi\Source\Repos\QlikSenseTask\QlikSenseTaskSource-3.X\QlikSenseTask\Program.cs:line 160"
2021_10_12_20_49_01,Information,"Returning Errorlevel 8"
